on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: isort, black
        uses: wrboyce/python-lint-action@v1.0.0

      - name: pylint
        uses: gabriel-milan/action-pylint@v1
  
